---
- name: Set Redpanda RPM and GPG Key details
  set_fact:
    deb_link_actual: "{{ is_using_unstable | bool | ternary(deb_unstable_download_url, deb_download_url) }}"

- name: Download Redpanda DEBs to local machine
  ansible.builtin.get_url:
    url: "{{ deb_link_actual }}"
    dest: "{{ download_directory }}"
  delegate_to: localhost

- name: Create tarball of Redpanda DEBs
  ansible.builtin.archive:
    path: "{{ download_directory }}/redpanda*.deb"
    dest: "{{ download_directory }}/redpanda_debs.tar.gz"
    format: gz
    remove: true
  delegate_to: localhost
