---
redpanda_organization: redpanda-test
redpanda_cluster_id: redpanda

redpanda_mode: production
redpanda_admin_api_port: 9644
redpanda_kafka_port: 9092
redpanda_rpc_port: 33145

redpanda_use_staging_repo: false
redpanda_base_url: "https://dl.redpanda.com"

redpanda_install_status: present # If redpanda_version is set to latest, changing redpanda_install_status to latest will effect an upgrade, otherwise the currently installed version will remain
redpanda_rpk_opts: ""

redpanda_base_dir: /var/lib/redpanda
redpanda_data_directory: "{{ redpanda_base_dir }}/data"
repdanda_mount_dir: /mnt/vectorized/redpanda

redpanda_certs_dir: /etc/redpanda/certs
redpanda_csr_file: "{{ redpanda_certs_dir }}/node.csr"
redpanda_key_file: "{{ redpanda_certs_dir }}/node.key"
redpanda_cert_file: "{{ redpanda_certs_dir }}/node.crt"
redpanda_truststore_file: "{{ redpanda_certs_dir }}/truststore.pem"
node_exporter_version: "{{ node_exporter_custom_version | default('1.5.0') }}"
cloud_storage_credentials_source: "config_file"
cloud_storage_enable_remote_write: "true"
cloud_storage_enable_remote_read: "true"
rp_key_rpm: "{{ redpanda_base_url }}/public/redpanda/gpg.988A7B0A4918BC85.key"
rp_conf_loc_rpm: "/etc/yum.repos.d/redpanda-redpanda.repo"
rp_key_deb: "{{ redpanda_base_url }}/sMIXnoa7DK12JW4A/redpanda/gpg.988A7B0A4918BC85.key"
rp_conf_loc_deb: "/etc/apt/sources.list.d/redpanda.list"
rp_key_path_deb: "/usr/share/keyrings/redpanda-redpanda-archive-keyring.gpg"
rp_repo_signing_deb: "deb [signed-by=/usr/share/keyrings/redpanda-redpanda-archive-keyring.gpg] {{ redpanda_base_url }}/public/redpanda/deb/{{ansible_distribution | lower}} {{ ansible_distribution_release | lower }} main"
rp_repo_signing_src_deb: "deb-src [signed-by=/usr/share/keyrings/redpanda-redpanda-archive-keyring.gpg] {{ redpanda_base_url }}/public/redpanda/deb/{{ansible_distribution | lower}} {{ ansible_distribution_release | lower }} main"
rpm_prerequisite_packages:
  - curl
  - yum-utils
  - dnf-plugins-core
debian_prerequisite_packages:
  - debian-keyring
  - debian-archive-keyring
  - apt-transport-https
  - ca-certificates
  - gnupg
  - iotop
  - mdadm
  - xfsprogs
