---

redpanda_organization: redpanda-test
redpanda_cluster_id: redpanda

redpanda_mode: production
redpanda_admin_api_port: 9644
redpanda_kafka_port: 9092
redpanda_rpc_port: 33145

redpanda_use_staging_repo: false
redpanda_repo_debian: "{{ 'https://packages.vectorized.io/sMIXnoa7DK12JW4A/redpanda/cfg/setup/bash.deb.sh' if not redpanda_use_staging_repo|bool else 'https://dl.redpanda.com/E4xN1tVe3Xy60GTx/redpanda-unstable/setup.deb.sh' }}"
redpanda_repo_redhat: "{{ 'https://dl.redpanda.com/nzc4ZYQK3WRGd9sy/redpanda/cfg/setup/bash.rpm.sh' if not redpanda_use_staging_repo|bool else 'https://dl.redpanda.com/E4xN1tVe3Xy60GTx/redpanda-unstable/setup.rpm.sh' }}"
redpanda_repo_script: "{{ redpanda_repo_debian if ansible_os_family == 'Debian' else redpanda_repo_redhat }}"
redpanda_install_status: present # If redpanda_version is set to latest, changing redpanda_install_status to latest will effect an upgrade, otherwise the currently installed version will remain
redpanda_rpk_opts: ""

redpanda_data_directory: /var/lib/redpanda/data

redpanda_certs_dir: /etc/redpanda/certs
redpanda_csr_file: "{{ redpanda_certs_dir }}/node.csr"
redpanda_key_file: "{{ redpanda_certs_dir }}/node.key"
redpanda_cert_file: "{{ redpanda_certs_dir }}/node.crt"
redpanda_truststore_file: "{{ redpanda_certs_dir }}/truststore.pem"
node_exporter_version: "{{ node_exporter_custom_version | default('1.5.0') }}"
cloud_storage_credentials_source: "config_file"
cloud_storage_enable_remote_write: "true"
cloud_storage_enable_remote_read: "true"
rp_key_rpm: "https://dl.redpanda.com/public/redpanda/gpg.988A7B0A4918BC85.key"
rp_config_url_rpm: "https://dl.redpanda.com/public/redpanda/config.rpm.txt"
rp_conf_loc_rpm: "/etc/yum.repos.d/redpanda-redpanda.repo"
rp_key_deb: "https://dl.redpanda.com/sMIXnoa7DK12JW4A/redpanda/gpg.988A7B0A4918BC85.key"
rp_config_url_deb: "https://dl.redpanda.com/sMIXnoa7DK12JW4A/redpanda/config.deb.txt"
rp_conf_loc_deb: "/etc/apt/sources.list.d/redpanda.list"
rpm_prerequisite_packages:
  - curl
  - yum-utils
  - dnf-plugins-core
debian_prerequisite_packages:
  - debian-keyring
  - debian-archive-keyring
  - apt-transport-https
  - ca-certificates
  - gnupg
