- name: Print Kafka Connect inventory hostname
  debug:
    msg: "The inventory hostname is {{ inventory_hostname }}"

- name: Wait for API to return 200
  uri:
    url: "{{kafka_connect_http_protocol}}://{{ inventory_hostname }}:{{kafka_connect_rest_port}}/connector-plugins"
    status_code: 200
    validate_certs: false
    url_username: "{{kafka_connect_health_check_user}}"
    url_password: "{{kafka_connect_health_check_password}}"
    force_basic_auth: true
  register: result1
  until: result1.status == 200
  retries: 40
  delay: 10
  when: kafka_connect_authentication_type != 'mtls'
  ignore_errors: true