---
- name: Node dependencies - Set APT proxy
  template:
    src: apt_proxy.j2
    dest: /etc/apt/apt.conf.d/proxy.conf
    mode: 0644
  become: true
  when: https_proxy_value is defined and https_proxy_value | length > 0 and ansible_os_family == 'Debian'

- name: Node dependencies - fedora setup
  when: ansible_os_family == 'RedHat'
  tags:
    - node_deps
  block:
    - name: node dependencies - delete unused repos
      ansible.builtin.file:
        name: "{{item}}"
        state: absent
      with_items:
        - /etc/yum.repos.d/fedora-updates-modular.repo
        - /etc/yum.repos.d/fedora-cisco-openh264.repo
    - name: Node dependencies - install base deps
      ansible.builtin.package:
        name:
          - iotop
          - mdadm
          - xfsprogs
        state: present
      environment:
        https_proxy: "{{ rpm_proxy | default('') }}"

- name: Node dependencies - add additional debian repos
  tags:
    - node_deps
  when: ansible_distribution == 'Debian'
  ansible.builtin.apt_repository:
    repo: deb http://deb.debian.org/debian stretch-backports main
    state: present

- name: Node dependencies - update packages - debian
  tags:
    - node_deps
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
  when: ansible_os_family == 'Debian'
  environment:
    https_proxy: "{{ https_proxy_value | default('') }}"

- name: Node dependencies - Install Debian prerequisites
  package:
    name: "{{ debian_prerequisite_packages }}"
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'
  environment:
    https_proxy: "{{ https_proxy_value | default('') }}"

- name: Node dependencies - Install RPM packages
  package:
    name: "{{ rpm_prerequisite_packages }}"
    state: present
    update_cache: yes
  when: ansible_os_family == 'RedHat'
  environment:
    https_proxy: "{{ rpm_proxy | default('') }}"
