---
- name: Node dependencies - fedora setup
  when: ansible_os_family == 'RedHat'
  tags:
    - node_deps
  block:
    - name: Node dependencies - delete unused repos
      ansible.builtin.file:
        name: "{{item}}"
        state: absent
      with_items:
        - /etc/yum.repos.d/fedora-updates-modular.repo
        - /etc/yum.repos.d/fedora-cisco-openh264.repo
    - name: Node dependencies - install base deps
      ansible.builtin.package:
        name:
          - iotop
          - mdadm
          - xfsprogs
        state: present

- name: Node dependencies - add additional debian repos
  tags:
    - node_deps
  when: ansible_distribution == 'Debian'
  ansible.builtin.apt_repository:
    repo: deb http://deb.debian.org/debian stretch-backports main
    state: present

- name: Node dependencies - update packages - debian
  tags:
    - node_deps
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
  when: ansible_os_family == 'Debian'

- name: Install Debian prerequisites
  package:
    name: "{{ debian_prerequisite_packages }}"
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install RPM packages
  package:
    name: "{{ rpm_prerequisite_packages }}"
    state: present
    update_cache: yes
  when: ansible_os_family == 'RedHat'
