---
- name: Install Redpanda RPM
  ansible.builtin.include_tasks: install-rp-rpm.yml
  when: ansible_os_family == 'RedHat'

- name: Install Redpanda DEB
  ansible.builtin.include_tasks: install-rp-deb.yml
  when: ansible_os_family == 'Debian'

- name: Start Redpanda
  ansible.builtin.include_tasks: start-redpanda.yml
